INSERT INTO user_profil VALUES ('Assistant');
INSERT INTO user_profil VALUES ('Chef');
INSERT INTO user_profil VALUES ('CG');
INSERT INTO user_profil VALUES ('CD');
INSERT INTO user_profil VALUES ('CPR');
INSERT INTO user_profil VALUES ('ACDL');
INSERT INTO user_profil VALUES ('ACPRL');
INSERT INTO user_profil VALUES ('ACDE');
INSERT INTO user_profil VALUES ('ACPRE');

-- ID, NOM, SECTION ( G / S )
INSERT INTO province VALUES ('', 'Lyonnaise-Dauphiné-Savoie', 'G');
INSERT INTO province VALUES ('', 'Lyonnaise-Dauphiné-Savoie', 'S');

-- ID, NOM, PROVINCE
INSERT INTO district VALUES ('', 'Lyon Centre', '1');
INSERT INTO district VALUES ('', 'Lyon Ouest', '1');
INSERT INTO district VALUES ('', 'Beaujolais - Val de Saône', '1');
INSERT INTO district VALUES ('', 'Dauphiné', '1');
INSERT INTO district VALUES ('', 'Vallée du Rhône', '1');
INSERT INTO district VALUES ('', 'Ain', '1');
INSERT INTO district VALUES ('', 'Savoie', '1');
INSERT INTO district VALUES ('', 'Lyon Centre', '2'); 
INSERT INTO district VALUES ('', 'Lyon Ouest', '2');
INSERT INTO district VALUES ('', 'Beaujolais - Val de Saône', '2');
INSERT INTO district VALUES ('', 'Dauphiné', '2');
INSERT INTO district VALUES ('', 'Vallée du Rhône', '2');
INSERT INTO district VALUES ('', 'Ain', '2');
INSERT INTO district VALUES ('', 'Savoie', '2');

-- ID, NOM, DISTRICT 
INSERT INTO groupe VALUES ('', '2e Lyon', '1' );
INSERT INTO groupe VALUES ('', '4e Lyon', '1' );
INSERT INTO groupe VALUES ('', '6e Lyon', '1' );
INSERT INTO groupe VALUES ('', '2e Monts d\'Or', '1' );
INSERT INTO groupe VALUES ('', '1e Lyon', '8' );
INSERT INTO groupe VALUES ('', '3e Lyon', '8' );
INSERT INTO groupe VALUES ('', '5e Lyon', '8' );
INSERT INTO groupe VALUES ('', '7e Lyon', '8' );
INSERT INTO groupe VALUES ('', '1e Brignais', '9' );
INSERT INTO groupe VALUES ('', '1e Ste Foy-lès-Lyon', '9' );
INSERT INTO groupe VALUES ('', '1e Tassin', '9' );
INSERT INTO groupe VALUES ('', '3e Tassin', '9' );
INSERT INTO groupe VALUES ('', '2e Tassin', '2' );
INSERT INTO groupe VALUES ('', '2e Brignais', '2' );
INSERT INTO groupe VALUES ('', '1e Notre Dame des Dombes', '13' );
INSERT INTO groupe VALUES ('', '1e Bresse-Bugey', '13' );
INSERT INTO groupe VALUES ('', '2e Notre Dame des Dombes', '6' );
INSERT INTO groupe VALUES ('', '1e St Georges de Reneins', '10' );
INSERT INTO groupe VALUES ('', '3e St Georges de Reneins', '10' );
INSERT INTO groupe VALUES ('', '5e St Georges de Reneins', '10' );
INSERT INTO groupe VALUES ('', '2e St Georges de Reneins', '3' );
INSERT INTO groupe VALUES ('', '4e St Georges de Reneins', '3' );
INSERT INTO groupe VALUES ('', '6e St Georges de Reneins', '3' );
INSERT INTO groupe VALUES ('', '1e Bourgoin-Jallieu', '11' );
INSERT INTO groupe VALUES ('', '1e Chartreuse', '11' );
INSERT INTO groupe VALUES ('', '1e Grenoble', '11' );
INSERT INTO groupe VALUES ('', '1e Meylan', '11' );
INSERT INTO groupe VALUES ('', '2e Bourgoin-Jallieu', '4' );
INSERT INTO groupe VALUES ('', '2e Grenoble', '4' );
INSERT INTO groupe VALUES ('', '2e La Tronche', '4' );
INSERT INTO groupe VALUES ('', '2e St Egrève', '4' );
INSERT INTO groupe VALUES ('', '1e Annecy', '14' );
INSERT INTO groupe VALUES ('', '1e Chambéry', '14' );
INSERT INTO groupe VALUES ('', '3e Chambéry', '14' );
INSERT INTO groupe VALUES ('', '1e Pays de Gex', '14' );
INSERT INTO groupe VALUES ('', '2e Annecy', '7' );
INSERT INTO groupe VALUES ('', '2e Chambéry', '7' );
INSERT INTO groupe VALUES ('', '4e Chambéry', '7' );
INSERT INTO groupe VALUES ('', '2e Pays de Gex', '7' );
INSERT INTO groupe VALUES ('', '1e Montélimar', '12' );
INSERT INTO groupe VALUES ('', '1e Romans', '12' );
INSERT INTO groupe VALUES ('', '1e Valence', '12' );
INSERT INTO groupe VALUES ('', '1e Vienne Pélussin', '12' );
INSERT INTO groupe VALUES ('', '2e Chavanay', '5' );
INSERT INTO groupe VALUES ('', '2e Montélimar', '5' );
INSERT INTO groupe VALUES ('', '2e Valence', '5' );

-- ID, NOM
INSERT INTO branche VALUES ('', 'Jaune' ); 
INSERT INTO branche VALUES ('', 'Vert' ); 

-- ID, GROUPE, BRANCHE, NB_LOUP
INSERT INTO unite VALUES ('', '1', '1', '0');
INSERT INTO unite VALUES ('', '2', '1', '0');
INSERT INTO unite VALUES ('', '3', '1', '0');
INSERT INTO unite VALUES ('', '4', '1', '0');
INSERT INTO unite VALUES ('', '5', '1', '0');
INSERT INTO unite VALUES ('', '6', '1', '0');
INSERT INTO unite VALUES ('', '7', '1', '0');
INSERT INTO unite VALUES ('', '8', '1', '0');
INSERT INTO unite VALUES ('', '9', '1', '0');
INSERT INTO unite VALUES ('', '10', '1', '0');
INSERT INTO unite VALUES ('', '11', '1', '0');
INSERT INTO unite VALUES ('', '12', '1', '0');
INSERT INTO unite VALUES ('', '13', '1', '0');
INSERT INTO unite VALUES ('', '14', '1', '0');
INSERT INTO unite VALUES ('', '15', '1', '0');
INSERT INTO unite VALUES ('', '16', '1', '0');
INSERT INTO unite VALUES ('', '17', '1', '0');
INSERT INTO unite VALUES ('', '18', '1', '0');
INSERT INTO unite VALUES ('', '19', '1', '0');
INSERT INTO unite VALUES ('', '20', '1', '0');
INSERT INTO unite VALUES ('', '21', '1', '0');
INSERT INTO unite VALUES ('', '22', '1', '0');
INSERT INTO unite VALUES ('', '23', '1', '0');
INSERT INTO unite VALUES ('', '24', '1', '0');
INSERT INTO unite VALUES ('', '25', '1', '0');
INSERT INTO unite VALUES ('', '26', '1', '0');
INSERT INTO unite VALUES ('', '26', '1', '0');
INSERT INTO unite VALUES ('', '27', '1', '0');
INSERT INTO unite VALUES ('', '28', '1', '0');
INSERT INTO unite VALUES ('', '29', '1', '0');
INSERT INTO unite VALUES ('', '30', '1', '0');
INSERT INTO unite VALUES ('', '31', '1', '0');
INSERT INTO unite VALUES ('', '32', '1', '0');
INSERT INTO unite VALUES ('', '33', '1', '0');
INSERT INTO unite VALUES ('', '34', '1', '0');
INSERT INTO unite VALUES ('', '35', '1', '0');
INSERT INTO unite VALUES ('', '36', '1', '0');
INSERT INTO unite VALUES ('', '37', '1', '0');
INSERT INTO unite VALUES ('', '38', '1', '0');
INSERT INTO unite VALUES ('', '39', '1', '0');
INSERT INTO unite VALUES ('', '40', '1', '0');
INSERT INTO unite VALUES ('', '41', '1', '0');
INSERT INTO unite VALUES ('', '42', '1', '0');
INSERT INTO unite VALUES ('', '43', '1', '0');
INSERT INTO unite VALUES ('', '44', '1', '0');
INSERT INTO unite VALUES ('', '45', '1', '0');
INSERT INTO unite VALUES ('', '46', '1', '0');

INSERT INTO unite VALUES ('', '1', '2', '0');
INSERT INTO unite VALUES ('', '2', '2', '0');
INSERT INTO unite VALUES ('', '3', '2', '0');
INSERT INTO unite VALUES ('', '4', '2', '0');
INSERT INTO unite VALUES ('', '5', '2', '0');
INSERT INTO unite VALUES ('', '6', '2', '0');
INSERT INTO unite VALUES ('', '7', '2', '0');
INSERT INTO unite VALUES ('', '8', '2', '0');
INSERT INTO unite VALUES ('', '9', '2', '0');
INSERT INTO unite VALUES ('', '10', '2', '0');
INSERT INTO unite VALUES ('', '11', '2', '0');
INSERT INTO unite VALUES ('', '12', '2', '0');
INSERT INTO unite VALUES ('', '13', '2', '0');
INSERT INTO unite VALUES ('', '14', '2', '0');
INSERT INTO unite VALUES ('', '15', '2', '0');
INSERT INTO unite VALUES ('', '16', '2', '0');
INSERT INTO unite VALUES ('', '17', '2', '0');
INSERT INTO unite VALUES ('', '18', '2', '0');
INSERT INTO unite VALUES ('', '19', '2', '0');
INSERT INTO unite VALUES ('', '20', '2', '0');
INSERT INTO unite VALUES ('', '21', '2', '0');
INSERT INTO unite VALUES ('', '22', '2', '0');
INSERT INTO unite VALUES ('', '23', '2', '0');
INSERT INTO unite VALUES ('', '24', '2', '0');
INSERT INTO unite VALUES ('', '25', '2', '0');
INSERT INTO unite VALUES ('', '26', '2', '0');
INSERT INTO unite VALUES ('', '26', '2', '0');
INSERT INTO unite VALUES ('', '27', '2', '0');
INSERT INTO unite VALUES ('', '28', '2', '0');
INSERT INTO unite VALUES ('', '29', '2', '0');
INSERT INTO unite VALUES ('', '30', '2', '0');
INSERT INTO unite VALUES ('', '31', '2', '0');
INSERT INTO unite VALUES ('', '32', '2', '0');
INSERT INTO unite VALUES ('', '33', '2', '0');
INSERT INTO unite VALUES ('', '34', '2', '0');
INSERT INTO unite VALUES ('', '35', '2', '0');
INSERT INTO unite VALUES ('', '36', '2', '0');
INSERT INTO unite VALUES ('', '37', '2', '0');
INSERT INTO unite VALUES ('', '38', '2', '0');
INSERT INTO unite VALUES ('', '39', '2', '0');
INSERT INTO unite VALUES ('', '40', '2', '0');
INSERT INTO unite VALUES ('', '41', '2', '0');
INSERT INTO unite VALUES ('', '42', '2', '0');
INSERT INTO unite VALUES ('', '43', '2', '0');
INSERT INTO unite VALUES ('', '44', '2', '0');
INSERT INTO unite VALUES ('', '45', '2', '0');
INSERT INTO unite VALUES ('', '46', '2', '0');

-- Formation
INSERT INTO formation VALUES ('0', 'Non-Formé', '');
INSERT INTO formation VALUES ('1', 'Attestation de capacité', 'AC');
INSERT INTO formation VALUES ('2', 'CEP1', 'CEP1');
INSERT INTO formation VALUES ('3', 'CEP2', 'CEP2');
